In [1]:
import numpy as np

In [2]:
# Defining a scalar
x = 20

In [11]:
# Defining a row vector
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [9]:
print(f"shape:{y.shape}, \nlength:{len(y)}")

shape:(3,), 
length:3


In [15]:
# Defining column vector
z = np.array([[1, 2, 3]])
z.shape

(1, 3)

In [20]:
# Creating a matrix
a = np.array([[1, 2, 3], [3, 4, 5],[5, 6, 7]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [25]:
# Printing matrix shape, dimentions and size
print(f"Shape: {a.shape}")
print(f"Dimensions: {a.ndim}")
print(f"Size : {a.size}")

Shape: (3, 3)
Dimensions: 2
Size : 9


In [64]:
# Creating a tensor
ones = np.ones((3, 3, 3), dtype=int)
ones

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [65]:
# Printing matrix shape, dimentions and size
print(f"Shape: {ones.shape}")
print(f"Dimensions: {ones.ndim}")
print(f"Size : {ones.size}")

Shape: (3, 3, 3)
Dimensions: 3
Size : 27


In [66]:
# updating matrix
ones[0, 1] = [3, 4, 5] 
print(ones)

[[[1 1 1]
  [3 4 5]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [67]:
ones[0, 1:2]

array([[3, 4, 5]])

In [91]:
ones[0:, 0, :1] = np.array([100, 100, 100]).reshape(3,1)

In [92]:
print(ones)

[[[100   1   1]
  [  3   4   5]
  [  1   1   1]]

 [[100   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[100   1   1]
  [  1   1   1]
  [  1   1   1]]]


### Matrix Operations

In [97]:
A = np.matrix([[1, 2], [3, 4]])
B = np.ones([2,2], dtype=int)

In [98]:
A + B

matrix([[2, 3],
        [4, 5]])

In [100]:
A - B

matrix([[0, 1],
        [2, 3]])

In [101]:
A * B

matrix([[3, 3],
        [7, 7]])

In [106]:
A.dot(B)

matrix([[3, 3],
        [7, 7]])

In [103]:
A/B

matrix([[1., 2.],
        [3., 4.]])

In [108]:
A

matrix([[1, 2],
        [3, 4]])

In [109]:
A.transpose()

matrix([[1, 3],
        [2, 4]])